{{- if .Values.postgresql.enabled }}
{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gh-bot-orchestrator.postgresql.fullname" . }}
  labels:
    {{- include "gh-bot-orchestrator.postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
{{- else if and .Values.externalDatabase.password (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-external-db" (include "gh-bot-orchestrator.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "gh-bot-orchestrator.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.externalDatabase.password | quote }}
{{- end }}
