{{- if not .Values.app.github.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gh-bot-orchestrator.github.secretName" . }}
  labels:
    {{- include "gh-bot-orchestrator.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-app-id: {{ .Values.app.github.auth.appId | quote }}
  github-installation-id: {{ .Values.app.github.auth.installationId | quote }}
  github-private-key: {{ .Values.app.github.auth.privateKey | quote }}
{{- end }}
