app:
  github:
    server:
      base-url: https://api.github.com
    auth:
      token-time-to-live: 1H
      installation-id: 56833735
      app-id: 1048033
  tasks:
    handle-pull-request-change:
      sleep-duration: 1s
  cleanup:
    workflow-run-availability:
      interval: PT5M
      max-age: PT10M
db-scheduler:
  enabled: true
  threads: 1
  polling-interval: 1s
  polling-strategy: LOCK_AND_FETCH
  polling-strategy-lower-limit-fraction-of-threads: 0.5
  polling-strategy-upper-limit-fraction-of-threads: 1.0
  allegro:
    retry-delay: 10s
    default-execution-delay: 0
    metrics:
      succeeded:
        refreshIntervalInMs: 3600000
    executor:
      task-queue-size: 100
      keep-alive-time: 600s
      request-timeout: 45s
    task-log:
      enabled: true
      retention:
        enabled: true
        cleanup-succeeded-tasks-after-days: 7
        cleanup-task-execution-cron: "0 0 3 * * *"
    maintenance:
      task-endpoint:
        enabled: true

spring:
  aop:
    proxy-target-class: false
  docker:
    compose:
      enabled: false

andamio:
  metrics:
    autogenerate-class-method-tags: true

logging:
  level:
    pl.allegro.tech.common.pullrequestmanager.domain.filtering: DEBUG
    pl.allegro.tech.common.pullrequestmanager.application.PullRequestEventHandler: DEBUG
